# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wss', '0002_auto_20170505_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyChoice',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='SurveyQuestion',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='SurveySection',
            new_name='Section',
        ),
    ]
